# ●顶部导航菜单
menu:
  首页: / || fas fa-home
  目录||fa-fw fas fa-compass:
    归档: /archives/ || fas fa-archive
    标签: /tags/ || fas fa-tags
    分类: /categories/ || fas fa-folder-open
  列表||fas fa-list:
    音乐: /music/ || fas fa-music
    视频: /movies/ || fas fa-video
  链接: /link/ || fas fa-link
  关于: /about/ || fas fa-heart

# ●代码块样式
highlight_theme: light # 代码块主题:darker/pale night/light/ocean/mac/mac light/false
highlight_copy: true # 复制按钮
highlight_lang: true # 显示代码语言类型
highlight_shrink: none # 是否收缩代码块 | none: 展开代码，隐藏收缩按钮。
highlight_height_limit:  # 代码块限制高度，单位: px
code_word_wrap: true # 代码不换行

# ●允许复制页面内容
copy:
  enable: true
  copyright:
    enable: true # 复制页面内容时，追加版权信息。
    limit_count: 50 # 超过50个字节，就追加版权信息

# ●首页个人信息板块，社交图标设置
social:
    fab fa-qq: /about/ || QQ
    fas fa-envelope: /about/ || 邮箱
    fab fa-weixin: /about/ || 微信

# ●开启本地搜索
local_search:
  enable: true

# ●网站favicon图标
favicon: https://cdn.jsdelivr.net/gh/zbglz/cdn@master/images/hexo/theme/butterfly/favicon.png

# ●首页个人信息板块头像。
avatar:
  img: https://cdn.jsdelivr.net/gh/zbglz/cdn@master/images/hexo/theme/butterfly/favicon.png
  effect: false

# ●移除所有顶部banner图
disable_top_img: false

# 归档: /archives/ 标签: /tags/ 分类: /categories/
# 音乐: /music/ 视频: /movies/ 链接: /link/ 关于: /about/ 

# ●首页顶部banner图，index_img
index_img: 

# ●默认banner图，top_img，如果页面(全部页面)未设置banner就显示这个banner
default_top_img: https://cdn.jsdelivr.net/gh/zbglz/cdn@master/images/hexo/theme/butterfly/top_img.jpg

# ●archives归档页banner，缺省显示default_top_img。
archive_img: https://cdn.jsdelivr.net/gh/zbglz/cdn@master/images/hexo/theme/butterfly/archive_img.jpg

# ●tag页面的banner，缺省显示default_top_img。
tag_img: 

# 给每个tag单独设置banner
tag_per_img:
  - hexo: https://cdn.jsdelivr.net/gh/zbglz/cdn@master/images/hexo/theme/butterfly/favicon.png
  - demo: https://cdn.jsdelivr.net/gh/zbglz/cdn@master/images/hexo/theme/butterfly/favicon.png

